name: Daily Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00 UTC (midnight)

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        # uses: jtalk/url-health-check-action@v4
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://one1-20simpletodo.onrender.com
          follow-redirect: true
          max-attempts: 5
          retry-delay: 10s