paths:
  /api/commodity:
    get:
      summary: Get all commodities
      tags:
        - Commodities
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination
      responses:
        '200':
          description: List of commodities
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Commodity'

    post:
      summary: Create a new commodity
      security:
        - bearerAuth: []
      tags:
        - Commodities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Commodity'
      responses:
        '201':
          description: Commodity created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commodity'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin only)

  /api/commodity/{id}:
    get:
      summary: Get commodity by ID
      tags:
        - Commodities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Commodity found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commodity'
        '404':
          description: Commodity not found

    patch:
      summary: Update commodity by ID
      security:
        - bearerAuth: []
      tags:
        - Commodities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Commodity'
      responses:
        '200':
          description: Commodity updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin only)
        '404':
          description: Commodity not found

    delete:
      summary: Delete commodity by ID
      security:
        - bearerAuth: []
      tags:
        - Commodities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Commodity deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin only)
        '404':
          description: Commodity not found

  /api/commodity/{id}/comments:
    post:
      summary: Add a comment to a commodity
      security:
        - bearerAuth: []
      tags:
        - Commodities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                text:
                  type: string
                rating:
                  type: integer
                  minimum: 0
                  maximum: 5
      responses:
        '200':
          description: Comment added successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Commodity not found

    delete:
      summary: Clear all comments from a commodity
      security:
        - bearerAuth: []
      tags:
        - Commodities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comments cleared successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin only)
        '404':
          description: Commodity not found
