tags:
  - name: Participants
    description: API for managing participants

paths:
  /api/participant:
    get:
      summary: Get all participants (admin only)
      tags:
        - Participants
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of all participants
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Participant'
        '401':
          description: Unauthorized - token missing or invalid
        '500':
          description: Server error fetching participants

    post:
      summary: Create a new participant
      tags:
        - Participants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                name:
                  type: string
                  example: Alkis
                surname:
                  type: string
                  example: Papadopoulos
                email:
                  type: string
                  example: alkis@example.com
                user:        # ✅ optional field (not from token)
                  type: string
                  description: "MongoDB ObjectId of the associated User (optional)"
                  example: 68aebb7d2a47dd01e42ff0e4
                transactions:
                  type: array
                  items:
                    type: string
                    example: 507f1f77bcf86cd799439011
      responses:
        '201':
          description: Participant created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  surname:
                    type: string
                  email:
                    type: string
                  user:          # ✅ now returned in response
                    type: string
                    description: "MongoDB ObjectId of linked User"
                  transactions:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid input or request body
  /api/participant/by-email:
    get:
      summary: Find participant by email
      tags:
        - Participants
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
          description: Email of the participant
      responses:
        '200':
          description: Participant found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      surname:
                        type: string
                      email:
                        type: string
        '400':
          description: Email missing
        '404':
          description: Participant not found
          
  /api/participant/{id}:
    get:
      summary: Find participant by ID
      tags:
        - Participants
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the participant
      responses:
        '200':
          description: Participant found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      surname:
                        type: string
                      email:
                        type: string
        '400':
          description: ID missing
        '404':
          description: Participant not found

    delete:
      summary: Delete a participant by ID
      tags:
        - Participants
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the participant to delete
          schema:
            type: string
      responses:
        '200':
          description: Participant deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: participant alkis@example.com deleted successfully
        '404':
          description: Participant not found
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  schemas:
    Participant:
      type: object
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        name:
          type: string
          example: Alkis
        surname:
          type: string
          example: Papadopoulos
        email:
          type: string
          example: alkis@example.com
        transactions:
          type: array
          items:
            type: string
            example: 64f1b8a97c05f9a4d9d12345
