paths:
  /api/stripe/checkout/{price_id}:
    post:
      tags:
        - Stripe
      summary: Create a Stripe Checkout Session
      description: Creates a new Stripe Checkout Session for a given price_id. Optionally, participant info can be included in the request body and will be stored as metadata.
      parameters:
        - in: path
          name: price_id
          required: true
          schema:
            type: string
          description: The Stripe Price ID for the item/donation.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                participantInfo:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "John"
                    surname:
                      type: string
                      example: "Doe"
                    email:
                      type: string
                      format: email
                      example: "john.doe@example.com"
      responses:
        '200':
          description: Checkout Session successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: object
                    description: Stripe Checkout Session object
        '400':
          description: Invalid request
        '500':
          description: Server error

  /api/stripe/success:
    get:
      tags:
        - Stripe
      summary: Handle successful payment
      description: Called after a successful Stripe Checkout. Records the transaction and updates the participant in the database.
      parameters:
        - in: query
          name: session_id
          required: true
          schema:
            type: string
          description: Stripe Checkout Session ID
      responses:
        '200':
          description: Transaction recorded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Transaction'
        '400':
          description: Missing or invalid session ID
        '409':
          description: Transaction already recorded
        '500':
          description: Server error

  /api/stripe/cancel:
    get:
      tags:
        - Stripe
      summary: Handle canceled payment
      description: Called after a canceled Stripe Checkout. Does not modify the database.
      responses:
        '200':
          description: Payment canceled response
          content:
            text/plain:
              schema:
                type: string
                example: "Payment canceled! :("
