openapi: 3.0.3
info:
  title: SubPage API
  version: 1.0.0
  description: API for managing subpages.

paths:
  /api/subpage:
    get:
      summary: Get all subpages
      tags: [SubPages]
      responses:
        '200':
          description: List of subpages
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
    post:
      summary: Create a subpage
      tags: [SubPages]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Subpage created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time

  /api/subpage/{subPageId}:
    put:
      summary: Edit a subpage
      tags: [SubPages]
      parameters:
        - name: subPageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated subpage
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
    delete:
      summary: Delete a subpage
      tags: [SubPages]
      parameters:
        - name: subPageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subpage deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
